<!DOCTYPE Payments [
<!ELEMENT Payments (Payment+)>
<!ELEMENT Payment (bookingID, carID, date, cost, method)>
<!ATTLIST Payment paymentID CDATA #REQUIRED>
<!ELEMENT bookingID (#PCDATA)>
<!ELEMENT carID (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT method (#PCDATA)>
]>

<Payments>
    <Payment paymentID="1234">
        <bookingID>001</bookingID>
        <carID>001</carID>
        <date>20/11/24</date>
        <cost>150.00</cost>
        <method>Visa</method>
    </Payment>
    <Payment paymentID="1235">
        <bookingID>002</bookingID>
        <carID>002</carID>
        <date>01/12/24</date>
        <cost>200.00</cost>
        <method>MasterCard</method>
    </Payment>
    <Payment paymentID="1236">
        <bookingID>003</bookingID>
        <carID>003</carID>
        <date>05/12/24</date>
        <cost>175.50</cost>
        <method>Visa</method>
    </Payment>
    <Payment paymentID="1237">
        <bookingID>004</bookingID>
        <carID>004</carID>
        <date>20/12/24</date>
        <cost>120.00</cost>
        <method>Visa</method>
    </Payment>
    <Payment paymentID="1238">
        <bookingID>005</bookingID>
        <carID>005</carID>
        <date>29/012/24</date>
        <cost>250.75</cost>
        <method>Visa</method>
    </Payment>
</Payments>
